steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/nca-toolkit-api', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/nca-toolkit-api']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'nca-toolkit-api'
      - '--image'
      - 'gcr.io/$PROJECT_ID/nca-toolkit-api'
      - '--region'
      - 'asia-southeast1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '16Gi'
      - '--cpu'
      - '4'
      - '--cpu-boost'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '5'
      - '--timeout'
      - '300s'

images:
  - 'gcr.io/$PROJECT_ID/nca-toolkit-api'

# Add logging options to fix the service account error
options:
  logging: CLOUD_LOGGING_ONLY