[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "/app/run_gunicorn.sh"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[service]
healthcheckPath = "/"
healthcheckTimeout = 10
healthcheckInterval = 30

[[services.ports]]
port = 8080
protocol = "tcp"
