name: Deploy to Railway

on:
  push:
    branches:
      - main
      - 'feature/**'
      - 'deploy/**'
  workflow_dispatch:  # Allow manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      
      - name: Install Railway CLI
        run: |
          echo "Installing Railway CLI..."
          npm install -g @railway/cli
          echo "Railway CLI version:"
          railway --version
      
      - name: Debug Environment
        run: |
          echo "Debug: Checking environment setup..."
          echo "Node version: $(node --version)"
          echo "NPM version: $(npm --version)"
          echo "Current directory: $(pwd)"
          echo "Directory contents:"
          ls -la
          echo "Railway CLI help:"
          railway --help
      
      - name: Create Project Config
        run: |
          echo "Debug: Creating temporary railway.json file..."
          echo '{"projectId":"${{ secrets.RAILWAY_PROJECT_ID }}"}' > railway.json
          echo "railway.json created:"
          cat railway.json
      
      - name: Deploy to Railway
        run: |
          echo "Debug: Starting deployment to Railway..."
          echo "Using RAILWAY_TOKEN for authentication"
          echo "Project ID from railway.json: $(cat railway.json | grep projectId)"
          echo "Running railway up command..."
          railway up
          echo "Deployment completed successfully"
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
