name: Deploy to Railway

on:
  push:
    branches:
      - main
      - 'feature/**'
      - 'deploy/**'
  workflow_dispatch:  # Allow manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      
      - name: Install Railway CLI
        run: npm install -g @railway/cli
      
      - name: Configure Railway
        run: |
          echo "Configuring Railway project..."
          # Store the project ID in a temporary file
          echo '{"projectId":"${{ secrets.RAILWAY_PROJECT_ID }}"}' > .railway-project-config.json
      
      - name: Deploy to Railway
        run: |
          echo "Deploying to Railway..."
          # Use the project config file
          railway up --config .railway-project-config.json
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
